In [1]:
from datetime import datetime
import MetaTrader5 as mt5
import pandas as pd
import pytz
import math as ma
import talib as ta

# display data on the MetaTrader 5 package 
print("MetaTrader5 package author: ",mt5.__author__) 
print("MetaTrader5 package version: ",mt5.__version__) 
  
# import the 'pandas' module for displaying data obtained in the tabular form
pd.set_option('display.max_columns', 500) # number of columns to be displayed
pd.set_option('display.width', 5500)      # max table width to display
# import pytz module for working with time zone


# establish connection to MetaTrader 5 terminal 
if not mt5.initialize():
    print("initialize() failed, error code =",mt5.last_error()) 
    quit()
 
# set time zone to UTC
timezone = pytz.timezone("Etc/UTC")
print(timezone)
# create 'datetime' objects in UTC time zone to avoid the implementation of a local time zone offset
str1='mt5.TIMEFRAME_D1'
utc_from = datetime(2020, 9, 15, tzinfo=timezone)
utc_to = datetime(2020, 9, 25, hour = 13, tzinfo=timezone)
# get bars from USDJPY M5 within the interval of 2020.01.10 00:00 - 2020.01.11 13:00 in UTC time zone
rates = mt5.copy_rates_range("GOLD", mt5.TIMEFRAME_D1, utc_from, utc_to)
rate1 = mt5.copy_rates_range("GOLD", mt5.TIMEFRAME_M1, utc_from, utc_to)
 
# shut down connection to the MetaTrader 5 terminal
mt5.shutdown() 

# display each element of obtained data in a new line
print("Display obtained data 'as is'")
counter=0
for rate in rates:
    counter+=1
    if counter<=10:
        print(rate)
 
# create DataFrame out of the obtained data
rates_frame = pd.DataFrame(rates)
rate1_frame = pd.DataFrame(rate1)
# convert time in seconds into the 'datetime' format
rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
rates_frame['ATR']=round(ta.ATR(rates_frame['high'],rates_frame['low'],rates_frame['close'],timeperiod=1)
,2) 
rate1_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
rate1_frame['ATR']=round(ta.ATR(rate1_frame['high'],rate1_frame['low'],rate1_frame['close'],timeperiod=1)
,2) 
# display data
print("\nDisplay dataframe with data")
print(rates_frame.tail(10))
print("\nDisplay dataframe with data") 
print(rate1_frame.tail(10))
#rates_frame.describe()
filepath='D:/DesktopSunti/mydataGOLDD2.csv'
rates_frame.to_csv(filepath, index=False, header=False)

print(rates_frame.describe())
print(rate1_frame.describe())
#rates_frame.quantile([.25,.5,.75])
#print(rates_frame.max())
#rates_frame['ATR'].value_counts(bins=20,sort=False)

MetaTrader5 package author:  MetaQuotes Software Corp.
MetaTrader5 package version:  5.0.33
Etc/UTC
Display obtained data 'as is'
(1600128000, 1956.74, 1972.03, 1948.21, 1954.1, 54983, 27, 0)
(1600214400, 1952.99, 1973.44, 1949.86, 1959.38, 60369, 33, 0)
(1600300800, 1959.08, 1960.89, 1932.82, 1944.03, 64592, 33, 0)
(1600387200, 1943.89, 1960.04, 1943.83, 1949.45, 56512, 26, 0)
(1600646400, 1949.65, 1955.47, 1882.7, 1912.46, 70553, 28, 0)
(1600732800, 1911.98, 1919.89, 1894.58, 1899.93, 72570, 33, 0)
(1600819200, 1899.97, 1905.24, 1855.65, 1863.04, 82715, 33, 0)
(1600905600, 1863.1, 1876.89, 1848.66, 1867.53, 85869, 23, 0)
(1600992000, 1867.97, 1874.97, 1852.28, 1860.71, 70588, 26, 0)

Display dataframe with data
        time     open     high      low    close  tick_volume  spread  real_volume    ATR
0 2020-09-15  1956.74  1972.03  1948.21  1954.10        54983      27            0    NaN
1 2020-09-16  1952.99  1973.44  1949.86  1959.38        60369      33            0  23.58
2 2020-09-17  1959.08  1960.89  1932.82  1944.03        64592      33            0  28.07
3 2020-09-18  1943.89  1960.04  1943.83  1949.45        56512      26            0  16.21
4 2020-09-21  1949.65  1955.47  1882.70  1912.46        70553      28            0  72.77
5 2020-09-22  1911.98  1919.89  1894.58  1899.93        72570      33            0  25.31
6 2020-09-23  1899.97  1905.24  1855.65  1863.04        82715      33            0  49.59
7 2020-09-24  1863.10  1876.89  1848.66  1867.53        85869      23            0  28.23
8 2020-09-25  1867.97  1874.97  1852.28  1860.71        70588      26            0  22.69

Display dataframe with data
      time     open     high      low    close  tick_volume  spread  real_volume   ATR
11739  NaT  1865.30  1865.52  1864.98  1865.24           73      33            0  0.54
11740  NaT  1865.20  1865.43  1864.34  1864.47           80      33            0  1.09
11741  NaT  1864.51  1865.80  1864.49  1865.66           70      33            0  1.33
11742  NaT  1865.68  1865.91  1865.38  1865.47           64      33            0  0.53
11743  NaT  1865.41  1865.50  1864.62  1864.67           67      33            0  0.88
11744  NaT  1864.67  1865.26  1864.36  1865.23           71      33            0  0.90
11745  NaT  1865.28  1865.97  1865.26  1865.88           65      33            0  0.74
11746  NaT  1865.90  1866.10  1865.81  1866.04           68      33            0  0.29
11747  NaT  1866.02  1866.25  1865.66  1866.12           71      33            0  0.59
11748  NaT  1866.17  1866.20  1865.15  1865.33           73      33            0  1.05
              open         high          low        close   tick_volume     spread  real_volume        ATR
count     9.000000     9.000000     9.000000     9.000000      9.000000   9.000000          9.0   8.000000
mean   1922.818889  1933.206667  1900.954444  1912.292222  68750.111111  29.111111          0.0  33.306250
std      38.330806    39.734380    43.314012    41.225223  10817.415917   3.919325          0.0  18.667241
min    1863.100000  1874.970000  1848.660000  1860.710000  54983.000000  23.000000          0.0  16.210000
25%    1899.970000  1905.240000  1855.650000  1867.530000  60369.000000  26.000000          0.0  23.357500
50%    1943.890000  1955.470000  1894.580000  1912.460000  70553.000000  28.000000          0.0  26.690000
75%    1952.990000  1960.890000  1943.830000  1949.450000  72570.000000  33.000000          0.0  33.570000
max    1959.080000  1973.440000  1949.860000  1959.380000  85869.000000  33.000000          0.0  72.770000
               open          high           low         close   tick_volume        spread  real_volume           ATR
count  11749.000000  11749.000000  11749.000000  11749.000000  11749.000000  11749.000000      11749.0  11748.000000
mean    1921.750169   1922.107493   1921.380716   1921.741846     49.196612     33.711975          0.0      0.736991
std       38.209343     38.128785     38.283428     38.209554     24.370100      3.231339          0.0      0.567866
min     1848.750000   1849.010000   1848.660000   1848.740000      1.000000     23.000000          0.0      0.000000
25%     1887.730000   1888.180000   1887.280000   1887.740000     30.000000     33.000000          0.0      0.350000
50%     1941.650000   1941.980000   1941.300000   1941.640000     48.000000     33.000000          0.0      0.590000
75%     1954.010000   1954.240000   1953.760000   1954.000000     68.000000     33.000000          0.0      0.960000
max     1972.920000   1973.440000   1972.590000   1972.850000    116.000000     87.000000          0.0      7.690000

In [2]:
print(rates_frame['time'][rates_frame['high'].idxmax()])
print(rates_frame['open'][rates_frame['high'].idxmax()])

2020-09-16 00:00:00
1952.99

In [3]:
bmax=ma.ceil(rates_frame['ATR'][rates_frame['ATR'].idxmax()])
bmin=ma.floor(rates_frame['ATR'][rates_frame['ATR'].idxmin()])
allRange=bmax-bmin
sStep=allRange/10
print(bmax,bmin,allRange,sStep)
r1=bmin
r2=r1+sStep
r3=r2+sStep
r4=r3+sStep
r5=r4+sStep
r6=r5+sStep
r7=r6+sStep
r8=r7+sStep
r9=r8+sStep
r10=r9+sStep
r11=r10+sStep
ranges=[r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11]
print(r1,r11)
print(rates_frame['ATR'].value_counts(bins=ranges,sort=False)/19*100)
ranges=[25,28,31]
print(rates_frame['ATR'].value_counts(bins=ranges,sort=False)/19*100)

73 16 57 5.7
16 73.00000000000001
(15.999, 21.7]     5.263158
(21.7, 27.4]      15.789474
(27.4, 33.1]      10.526316
(33.1, 38.8]       0.000000
(38.8, 44.5]       0.000000
(44.5, 50.2]       5.263158
(50.2, 55.9]       0.000000
(55.9, 61.6]       0.000000
(61.6, 67.3]       0.000000
(67.3, 73.0]       5.263158
Name: ATR, dtype: float64
(24.999, 28.0]     5.263158
(28.0, 31.0]      10.526316
Name: ATR, dtype: float64

In [4]:
bmax=ma.ceil(rate1_frame['ATR'][rate1_frame['ATR'].idxmax()])
bmin=ma.floor(rate1_frame['ATR'][rate1_frame['ATR'].idxmin()])
allRange=bmax-bmin
sStep=allRange/10
print(bmax,bmin,allRange,sStep)
r1=bmin
r2=r1+sStep
r3=r2+sStep
r4=r3+sStep
r5=r4+sStep
r6=r5+sStep
r7=r6+sStep
r8=r7+sStep
r9=r8+sStep
r10=r9+sStep
r11=r10+sStep
ranges=[r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11]
print(r1,r11)
print(rate1_frame['ATR'].value_counts(bins=ranges,sort=False)/11749*100)
ranges=[0,.2,.4,.6,.8]
print(rate1_frame['ATR'].value_counts(bins=ranges,sort=False)/11749*100)
ranges=[1,7.4]
print(rate1_frame['ATR'].value_counts(bins=ranges,sort=False)/11749*100)

8 0 8 0.8
0 7.999999999999999
(-0.001, 0.8]    66.626947
(0.8, 1.6]       25.900077
(1.6, 2.4]        5.753681
(2.4, 3.2]        1.200102
(3.2, 4.0]        0.348966
(4.0, 4.8]        0.059580
(4.8, 5.6]        0.051068
(5.6, 6.4]        0.025534
(6.4, 7.2]        0.008511
(7.2, 8.0]        0.017023
Name: ATR, dtype: float64
(-0.001, 0.2]     9.200783
(0.2, 0.4]       21.440123
(0.4, 0.6]       20.759214
(0.6, 0.8]       15.226828
Name: ATR, dtype: float64
(0.999, 7.4]    23.287088
Name: ATR, dtype: float64